/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAO_AtorFilme;
import Model.AtorFilme;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class ConsultaAtorFilme extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaAtorFilme
     */
    public ConsultaAtorFilme() {
        initComponents();
        listaAtorFilme();
    }
    
    private void listaAtorFilme() {
        DefaultTableModel tabela = (DefaultTableModel) tblAtorFilme.getModel();
        tabela.setNumRows(0);
        
        DAO.DAO_AtorFilme objAtorFilme = new DAO_AtorFilme();
        ResultSet dados = objAtorFilme.listaAtorFilme();
        
        try {
            while(dados.next()) {
                tabela.addRow( new Object[] {
                   dados.getString(1),
                   dados.getString(2),
                   dados.getString(3),
                   dados.getString(4),
                   dados.getString(5),
                });
            }
        } catch(SQLException error) {
            throw new RuntimeException(error.getMessage());
        }
    }
    
    private void pesquisaAtorFilme() {
        
        String pesquisa = campoPesquisa.getText();
        DefaultTableModel tabela = (DefaultTableModel) tblAtorFilme.getModel();
        tabela.setNumRows(0);
        
        DAO.DAO_AtorFilme objAtorFilme = new DAO_AtorFilme();
        ResultSet dados = objAtorFilme.pesquisaAtorFilme(pesquisa);
        
        try {
            while(dados.next()) {
                tabela.addRow( new Object[] {
                   dados.getString(1),
                   dados.getString(2),
                   dados.getString(3),
                   dados.getString(4),
                   dados.getString(5),
                });
            }
        } catch(SQLException error) {
            throw new RuntimeException(error.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAtorFilme = new javax.swing.JTable();
        btCadastrar1 = new javax.swing.JButton();
        btAlterar1 = new javax.swing.JButton();
        btExcluir2 = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        btPesquisar1 = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(25, 25, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filme/Ator:");

        tblAtorFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Ator", "Código Filme", "Nome", "Filme"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAtorFilme.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblAtorFilme);

        btCadastrar1.setBackground(new java.awt.Color(85, 0, 0));
        btCadastrar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrar1.setText("Cadastrar");
        btCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrar1ActionPerformed(evt);
            }
        });

        btAlterar1.setBackground(new java.awt.Color(85, 0, 0));
        btAlterar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btAlterar1.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar1.setText("Alterar");
        btAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterar1ActionPerformed(evt);
            }
        });

        btExcluir2.setBackground(new java.awt.Color(85, 0, 0));
        btExcluir2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btExcluir2.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir2.setText("Excluir");
        btExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir2ActionPerformed(evt);
            }
        });

        btCancelar1.setBackground(new java.awt.Color(85, 0, 0));
        btCancelar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar1.setText("Cancelar");
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        btPesquisar1.setBackground(new java.awt.Color(85, 0, 0));
        btPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/magnifying-glass.png"))); // NOI18N
        btPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar1)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btCadastrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar1)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar1)
                    .addComponent(btAlterar1)
                    .addComponent(btExcluir2)
                    .addComponent(btCancelar1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrar1ActionPerformed
        CadAtorFilme consulta = new CadAtorFilme();
        
        consulta.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btCadastrar1ActionPerformed

    private void btAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterar1ActionPerformed
        
        String codigo, fk_id_ator, fk_id_filme, nome_ator, nome_filme;
        
        if(tblAtorFilme.getSelectedRow() < 0 ) {
            JOptionPane.showMessageDialog(this, "Selecione um campo para alterar!");
        } else {
            
            int linha = tblAtorFilme.getSelectedRow();
            
            codigo = (String) tblAtorFilme.getValueAt(linha, 0);
            fk_id_ator = (String) tblAtorFilme.getValueAt(linha, 1);
            fk_id_filme = (String) tblAtorFilme.getValueAt(linha, 2);
            nome_ator = (String) tblAtorFilme.getValueAt(linha, 3);
            nome_filme = (String) tblAtorFilme.getValueAt(linha, 4);
            
            AltAtorFilme altera = new AltAtorFilme();
            altera.setVisible(true);
            
            altera.resgate(fk_id_ator, fk_id_filme, nome_ator, nome_filme, codigo);
            this.dispose();
            
        }

        

    }//GEN-LAST:event_btAlterar1ActionPerformed

    private void btExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir2ActionPerformed
        // TODO add your handling code here:
        
        if(tblAtorFilme.getSelectedRow() < 0 ) {
            JOptionPane.showMessageDialog(this, "Selecione um campo para excluir!");
        } else {
            
            int linha = tblAtorFilme.getSelectedRow();
            
            String id = (String) tblAtorFilme.getValueAt(linha, 0);
            
            DAO.DAO_AtorFilme objAtorFilme = new DAO_AtorFilme();
            Model.AtorFilme atorFilme = new AtorFilme(id);
            
            int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este dado?");
            
            if(confirm == JOptionPane.YES_OPTION) {
                
                try {
                    objAtorFilme.exclui(atorFilme);
                    JOptionPane.showMessageDialog(this, "Filme excluido");
                } catch(HeadlessException error) {
                    JOptionPane.showMessageDialog(this, "Houve um erro ao excluir filme" + error.getMessage());
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Dado não excluido");
            }
        }
       
        listaAtorFilme();

    }//GEN-LAST:event_btExcluir2ActionPerformed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        this.dispose();
        ConsultaAtor consulta = new ConsultaAtor();
        
        consulta.setVisible(true);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar1ActionPerformed
        // TODO add your handling code here:
        pesquisaAtorFilme();
    }//GEN-LAST:event_btPesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAtorFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAtorFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAtorFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAtorFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAtorFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar1;
    private javax.swing.JButton btCadastrar1;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btPesquisar1;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAtorFilme;
    // End of variables declaration//GEN-END:variables
}
