/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author erikv
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btConsultarCat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btConsultarDir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btConsultarAtor = new javax.swing.JButton();
        btConsultarDvd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btConsultarFilme = new javax.swing.JButton();
        btConsultarFilme1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoucaDora - Tela Inicial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(25, 25, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gêneros");

        btConsultarCat.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarCat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarCat.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarCat.setText("Consultar");
        btConsultarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarCatActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Loguinho.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Diretores");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" DVD's");

        btConsultarDir.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarDir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarDir.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarDir.setText("Consultar");
        btConsultarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarDirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Atores");

        btConsultarAtor.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarAtor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarAtor.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarAtor.setText("Consultar");
        btConsultarAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAtorActionPerformed(evt);
            }
        });

        btConsultarDvd.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarDvd.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarDvd.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarDvd.setText("Consultar");
        btConsultarDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarDvdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Filmes");

        btConsultarFilme.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarFilme.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarFilme.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarFilme.setText("Consultar");
        btConsultarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarFilmeActionPerformed(evt);
            }
        });

        btConsultarFilme1.setBackground(new java.awt.Color(85, 0, 0));
        btConsultarFilme1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConsultarFilme1.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarFilme1.setText("Consultar");
        btConsultarFilme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarFilme1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btConsultarDir)
                                .addGap(99, 99, 99)
                                .addComponent(btConsultarCat))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btConsultarDvd)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btConsultarAtor)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(23, 23, 23))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(125, 125, 125))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConsultarFilme1)
                            .addComponent(btConsultarFilme))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarDvd)
                    .addComponent(btConsultarAtor))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarCat)
                    .addComponent(btConsultarDir))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarFilme1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarFilmeActionPerformed
        ConsultaFilme consulta_filmes = new ConsultaFilme();
        consulta_filmes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultarFilmeActionPerformed

    private void btConsultarDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarDvdActionPerformed
        ConsultaDvd consulta_dvd = new ConsultaDvd();
        consulta_dvd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultarDvdActionPerformed

    private void btConsultarAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAtorActionPerformed
        ConsultaAtor consulta_ator = new ConsultaAtor();
        consulta_ator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultarAtorActionPerformed

    private void btConsultarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarDirActionPerformed
        ConsultaDiretor consulta_diretor = new ConsultaDiretor();
        consulta_diretor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultarDirActionPerformed

    private void btConsultarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarCatActionPerformed
        ConsultaGenero consulta_categoria = new ConsultaGenero();
        consulta_categoria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultarCatActionPerformed

    private void btConsultarFilme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarFilme1ActionPerformed
        // TODO add your handling code here:
        
        ConsultaUsuario consulta = new ConsultaUsuario();
        consulta.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btConsultarFilme1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarAtor;
    private javax.swing.JButton btConsultarCat;
    private javax.swing.JButton btConsultarDir;
    private javax.swing.JButton btConsultarDvd;
    private javax.swing.JButton btConsultarFilme;
    private javax.swing.JButton btConsultarFilme1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
